name: MoneyAPI
version: 1.0.0
author: ByteForge88
api: 5.36.0
main: byteforge88\moneyapi\MoneyAPI

permissions:
  moneyapi.balance:
    default: true
  moneyapi.seebalance:
    default: true
  moneyapi.pay:
    default: true
  moneyapi.addmoney:
    default: op
  moneyapi.removemoney:
    default: op
  moneyapi.setbalance:
    default: op